a12 = 'python'.find('th')
print(a12)
a12 = 'python'.find('TH')
print(a12)
a12 = '''Beautiful is better than ugly. Explicit is better than implicit.'''.split()
print(a12)
a13 = 'Beautiful is better than ugly. Explicit is better than implicit.'.split()
print(a13)
a14 = '-'.join(a12[:5])
print(a14)
a15 = '-'.join(a12[:1])
print(a15)
a16 = '-'.join(a12[:2])
print(a16)
a17 = '-'.join(a12[:3])
print(a17)
a18 = 'python'.startswith('py')
print(a18)
a18 = 'python'.startswith('yt')
print(a18)
a18 = ('jpg', 'png', 'gif')
print('image.png'.endswith(a18))
print('text.txt'.endswith(a18))
a19 = '가abcd나'
print(a19.encode('ascii', 'ignore'))
a19 = '가abcd나'
print(a19.encode('ascii', 'replace'))
a19 = '가abcd나'
print(a19.encode('ascii'))

