/* 대표 학과,전공,세부전공코드  */
SELECT BB.HG_CD
  FROM GRSCH.GBCOUR0300 AA
      , ADMIN.AABASE0100 BB
  WHERE AA.DEPT_CD = BB.DEPT_CD
    AND AA.YY = ?
    AND AA.TM_GBN = ?
    AND TO_NUMBER(BB.BREU_GBN) = TO_NUMBER(?)
    AND BB.COLG_CD = ?
    AND BB.HG_CD = ?
    AND NVL(AA.CLS_CLSS_YN,'0') = '0'
  GROUP BY BB.BREU_GBN ,BB.COLG_CD,BB.HG_CD