/* 대표 학과,전공,세부전공코드  */
SELECT D3.BREU_GBN AS MASTER_MAIN_CODE,
       D3.COLG_CD AS MASTER_ORGAN_CODE,
       D3.HG_CD AS MASTER_CLASS_CODE,
       D3.MJ_CD AS MASTER_MAJOR_CODE
  FROM TABLE(UNIVT.SF_UBBASE_RPST_DEPT_CD('')) C1,
       GRSCH.GASREG0100 D2,
       ADMIN.AABASE0100 D3
 WHERE D2.STUNO      = ?
   AND D2.CETE_DT  IS NULL
   AND D2.DEGR_ARD_DT  IS NULL
   AND NVL(D2.THSS_EXTNS_YN,'0') ='0'
   AND (D2.SCHREG_MOD_GBN  IN ('2', '4', '5') OR D2.SCHREG_MOD_GBN IS NULL)
   AND D2.DEPT_CD = C1.DEPT_CD
   AND C1.RPST_DEPT_CD = D3.DEPT_CD