/* 대학원 수강신청 내역 */
SELECT H6.HY AS GRADE,
       (SELECT COMMN.SF_CODE_NM('UB028', H1.DAYNGT_GBN) FROM DUAL) AS DAY_OPT,
       H6.LT_NO AS OPEN_GWAMOK_NO,
       H6.DIVCLS_CD AS BUNBAN_NO,
       H6.LT_NO||'-'||H6.DIVCLS_CD as HAKSU_NO,
       TO_CHAR(TO_NUMBER(DECODE(H1.TLSN_YRSYS_SINGLE_GBN,'00','',H1.TLSN_YRSYS_SINGLE_GBN))) AS GRADE_OPT,
       H6.CPTN_GBN AS OPEN_CODE,
       H1.HP AS HAKJUM_NUM,
       DECODE(H1.HP,'',DECODE(H1.PASS_SC_YN,'1','P'),H1.HP) AS HAKJUM,
       '' AS CULTURE_CODE,
       ADMIN.SF_STAF_GET_EMP_INFO(H1.MNGT_PROF_EMP_NO, 'NM') AS MEMBER_NAME,
       H2.SC_NM AS GWAMOK_KNAME,
       (SELECT SUBSTR(GRSCH.SF_GBCOUR_GET_COURTIME('LECTM',H6.YY,H6.TM_GBN,H6.LT_NO,H6.DIVCLS_CD),1,1) FROM DUAL) AS DAY,
       (SELECT REPLACE(SUBSTR(GRSCH.SF_GBCOUR_GET_COURTIME('LECTM',H6.YY,H6.TM_GBN,H6.LT_NO,H6.DIVCLS_CD),3),')','') FROM DUAL) AS TIME_NO,
       (SELECT GRSCH.SF_GBCOUR_GET_COURTIME('BUILD',H6.YY,H6.TM_GBN,H6.LT_NO,H6.DIVCLS_CD) FROM DUAL) AS LOC_NAME,
       DECODE(H1.PASS_SC_YN,'1','Y','0','','') AS PASS_OPT,
       (SELECT COMMN.SF_CODE_NM('UB001', H6.CPTN_GBN) FROM DUAL) AS ISU_NM,
       DECODE(H6.REPEAT_YN,'1','Y','')                           AS RESUGANG_OPT,
       (SELECT COMMN.SF_CODE_NM('EC201', H1.DEGR_GBN) FROM DUAL) AS DEGR_GBN_NM,
       DECODE(H1.HY,9,'제한없음',H1.HY||REPLACE(REPLACE((SELECT COMMN.SF_CODE_NM('UB017', H1.tlsn_yrsys_single_gbn) FROM DUAL),'해당',''),'이상','학년이상')) AS HY
  FROM GRSCH.GBCOUR0300 H1,
       GRSCH.GBCOUR0100 H2,
       GRSCH.GBTLSN0100 H6
 WHERE H6.YY        = ?
   AND H6.TM_GBN    = ?
   AND H6.STUNO     = ?
   AND H6.YY        = H1.YY(+)
   AND H6.TM_GBN    = H1.TM_GBN(+)
   AND H6.LT_NO     = H1.LT_NO(+)
   AND H6.DIVCLS_CD = H1.DIVCLS_CD(+)
   AND H1.SC_CD     = H2.SC_CD(+)