/* 장바구니 */
SELECT NVL(A.DEPT_TLSN_APLY_EXCLUS_YN,'0') AS DEPT_TLSN_APLY_EXCLUS_YN
     , NVL(B.STD_TLSN_APLY_LMT_YN,'0') AS STD_TLSN_APLY_LMT_YN
     , NVL(C.NOTI_MSG_CTNT,'') AS NOTI_MSG_CTNT
  FROM UNIVT.UBCOUR0300 A
     , UNIVT.UBBASE0510 B
     , UNIVT.UBBASE0500 C
 WHERE A.YY     = ?
   AND A.TM_GBN = ?
   AND A.LT_NO  = ?
   AND A.DIVCLS_CD = ?
   AND A.SC_CD = B.SC_CD(+)
   AND B.DEPT_CD = C.DEPT_CD(+)
   AND B.NOTI_MSG_CD = C.NOTI_MSG_CD(+)