/* 교과개설변경안내 */
SELECT CHG_GBN AS TERM_GUBUN,
       LT_NO ||'-'|| DIVCLS_CD AS HAKSU_NO,
       MJ_NM AS MAJOR_NAME,
       HY AS GRADE,
       CPTN_GBN AS OPEN_CODE,
       COMMN.SF_CODE_NM('UB001', CPTN_GBN) AS OPEN_NAME,
       SC_ENG_NM AS GWAMOK_NAME,
       RESP_PROF_NM AS MEMBER_NAME,
       LECTM_NM AS TIME_NO,
       LT_ROOM_NM AS LOC_NAME,
       AFTCHG_CTNT AS AFTER_NAME
  FROM UNIVT.UBCOUR0301
 WHERE YY   = ?
   AND TM_GBN           = ?
 ORDER BY CHG_GBN, LT_NO, DIVCLS_CD